#!/bin/sh
#
# chkconfig: 345 99 05
# description:  Start up the sms_gateway engine.


#Setup:
#1: cp sms_gateway  /etc/init.d/sms_gateway
#2: chmod 750 /etc/init.d/sms_gateway
#3: chkconfig --add sms_gateway
#4: chkconfig sms_gateway on
#Usage:
#Start service: service sms_gateway start
#Stop service: service sms_gateway stop

# Source function library.
. /etc/init.d/functions

RETVAL=$?

JAVA_HOME=/usr/java/latest
JAVA_OPTS="-Xms256m -Xmx2g"
PROGRAM_NAME=SMS-Gateway
PROGRAM_HOME=/home/smsgateway/smpp-client
PROGRAM_PID=$PROGRAM_HOME/sms-gateway.pid
PROGRAM_USER=smsgateway

DAEMON_START=$PROGRAM_HOME/sms-gateway.sh

export JAVA_HOME
export PROGRAM_HOME
export PROGRAM_NAME
export PROGRAM_PID
export JAVA_OPTS

test -f $DAEMON || exit 0

set -e

function showpid()
{
    PID=`cat $PROGRAM_PID`
    echo "PID=$PID"
}
start(){
                echo "Start $PROGRAM_NAME Service!"
                su - $PROGRAM_USER -c "cd $PROGRAM_HOME; ./sms-gateway.sh"
                touch /var/lock/subsys/sms-gateway.pid
}
stop(){
                if [ -s $PROGRAM_HOME"/sms-gateway.pid" ] #file containing pid exists
                then
                echo "Stop $PROGRAM_NAME Service!"
                set `cat $PROGRAM_HOME/sms-gateway.pid`
                echo "Killing $PROGRAM_NAME Proccess. PID= $1"
                kill $1
                rm $PROGRAM_HOME/sms-gateway.pid
                else
                echo "$PROGRAM_NAME not Started!"
                fi
                rm -f /var/lock/subsys/sms-gateway.pid
}

case "$1" in
 start)
                start
        ;;
 stop)
                stop
        ;;
 status)
                if [ -s $PROGRAM_HOME"/sms-gateway.pid" ]
                then
                        PID=`cat $PROGRAM_PID`
                        if `ps -p $PID > /dev/null` ;
                                then
                                echo "$PROGRAM_NAME is running, PID=$PID"
                        fi
        else
            echo "$PROGRAM_NAME is stopped"
        fi
        ;;
restart)
                stop && start
        ;;
 *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
exit $RETVAL
