SET DEFINE OFF;
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (1, 'vtl', '8496', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (2, 'vtl', '8497', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (3, 'vtl', '8498', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (4, 'vtl', '8416', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (5, 'vnp', '8494', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (6, 'vnp', '84123', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (7, 'vnp', '84125', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (8, 'vnp', '84127', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (9, 'vnp', '84129', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (10, 'vnp', '8491', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (11, 'vms', '8490', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (12, 'vms', '8493', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (13, 'vms', '84120', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (14, 'vms', '84121', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (15, 'vms', '84122', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (16, 'vnp', '84124', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (17, 'vms', '84126', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (18, 'vms', '84128', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (19, 'vnm', '8492', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (20, 'vnm', '84188', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (21, 'bee', '84992', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (22, 'bee', '84199', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (23, 'vnm', '84186', 12);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (24, 'lao', '856', 13);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (25, 'cam', '855', 13);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (26, 'bee', '84993', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (27, 'bee', '84994', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (28, 'bee', '84995', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (29, 'bee', '84996', 11);
Insert into SMSQUEUE.TBL_TELCO
   (TELCOID, TELCO_NAME, PREFIX_NUMBER, LEN_NUMBER)
 Values
   (30, 'bee', '84997', 11);
COMMIT;
